<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Rajiv" name="qa.crm.testcases.Page3" tests="1" failures="0" timestamp="10 Nov 2019 13:09:19 GMT" time="0.017" errors="1">
  <testcase name="Page3" time="0.017" classname="qa.crm.testcases.Page3">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at qa.crm.utility.TestUtility.CapatureScreenShot(TestUtility.java:22)
	at qa.crm.utility.TestListener.onTestStart(TestListener.java:16)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1747)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1722)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:459)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- Page3 -->
</testsuite> <!-- qa.crm.testcases.Page3 -->
